[colors]
background = "{{colors.background.default.hex}}"
foreground = "{{colors.on_surface.default.hex}}"
cursor_bg = "{{colors.primary.default.hex}}"
cursor_border = "{{colors.primary.default.hex}}"
cursor_fg = "{{colors.on_primary.default.hex}}"
selection_bg = "{{colors.secondary_fixed_dim.default.hex}}"
selection_fg = "{{colors.on_secondary.default.hex}}"

split = "{{colors.secondary_fixed_dim.default.hex}}"

ansi = [
    "#191919",
    "#D90202",
    "#7FB11B",
    "#FFD739",
    "#3570D7",
    "#BE84FF",
    "#66D9EF",
    "#F8F8F8"
]

brights = [
    "#4D4D4D",
    "#FF4747",
    "#A0D04D",
    "#FFEB4D",
    "#6A9FF7",
    "#D9A6FF",
    "#80F5FF",
    "#FFFFFF"
]

[colors.tab_bar]
background = "{{colors.surface_container_low.default.hex}}"
inactive_tab_edge = "{{colors.outline.default.hex}}"

[colors.tab_bar.active_tab]
bg_color = "{{colors.primary_container.default.hex}}"
fg_color = "{{colors.on_primary_container.default.hex}}"
intensity = 'Normal'

[colors.tab_bar.inactive_tab]
bg_color = "{{colors.surface_container.default.hex}}"
fg_color = "{{colors.on_surface_variant.default.hex}}"
intensity = 'Normal'

[colors.tab_bar.inactive_tab_hover]
bg_color = "{{colors.surface_container_high.default.hex}}"
fg_color = "{{colors.on_surface.default.hex}}"

[colors.tab_bar.new_tab]
bg_color = "{{colors.surface_container_low.default.hex}}"
fg_color = "{{colors.on_surface_variant.default.hex}}"
